### ISSUE TITLE
IGES support

### ISSUE THREAD

**Issue by fidoriel** [bschwind/opencascade-rs#184]
It would be very nice, if the OCCT iges importer would be supported within the high opencascade api abstraction like step is.

https://dev.opencascade.org/doc/overview/html/occt_user_guides__iges.html

**Comment by bschwind** [comment]
Yes, this can be added back in now that we have more upload space on crates.io for `occt-sys`

**Comment by fidoriel** [comment]
Oh, it was in there but has been removed, so everything is already done? Great.

**Comment by bschwind** [comment]
> Oh, it was in there but has been removed, so everything is already done?

Not quite - The C++ code was excluded via a [Cargo.toml exclude path](https://github.com/bschwind/opencascade-rs/blob/ba2a149aa79a642a444a8bdc10fd6f905d9a83dd/crates/occt-sys/Cargo.toml#L12) to get the crate size down, but it should now be included.

So the bindings were never there, but it should be straightforward to follow the bindings for STEP and STL import/export in order to add support for IGES.

**Comment by fidoriel** [comment]
> > Oh, it was in there but has been removed, so everything is already done?
> 
> Not quite - The C++ code was excluded via a [Cargo.toml exclude path](https://github.com/bschwind/opencascade-rs/blob/ba2a149aa79a642a444a8bdc10fd6f905d9a83dd/crates/occt-sys/Cargo.toml#L12) to get the crate size down, but it should now be included.
> 
> So the bindings were never there, but it should be straightforward to follow the bindings for STEP and STL import/export in order to add support for IGES.

Bindings were not difficult. Difficult was to understand which functions to call in the c++ classes.
